name:    cms-utils
version: 0.1.0

dependencies:

# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5

- classy-prelude-yesod

- blaze-colonnade
- blaze-html
- blaze-markup
- bytestring
- colonnade
- containers
- data-default
- mime-mail
- persistent
- shakespeare
- text
- time
- transformers
- yesod
- yesod-auth
- yesod-core
- yesod-form

library:
  source-dirs: src
  ghc-options: -Wall -Werror -fwarn-tabs
